name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Save output to artifact
        run: |
          python -c "import sys; print(sys.version)" > artifact_${{ matrix.python-version }}.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-version-artifacts
          path: |
            version_3.8.txt
            version_3.9.txt
            version_3.10.txt
