name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # GitHub 저장소를 체크아웃합니다.
      - uses: actions/checkout@v3

      # 파이썬 환경을 설정합니다.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 파이썬 버전을 출력하고 결과를 artifact.txt 파일에 저장합니다.
      - name: Display Python version and save to file
        run: |
          python -c "import sys; print(sys.version)" > artifact.txt
          # artifact.txt 파일의 내용을 출력합니다.
          cat artifact.txt
      
      # 아티팩트를 업로드합니다.
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # 아티팩트의 이름을 지정합니다.
          name: python-version-artifact
          # 업로드할 파일의 경로를 지정합니다.
          path: artifact.txt
