name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      # 파이썬 환경 설정
      - name: Python ${{ matrix.python-version }} 설정
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 파이썬 버전 출력 및 artifact.txt에 저장
      - name: Python 버전 출력 및 파일에 저장
        run: |
          python -c "import sys; print(sys.version)" > artifact.txt
          cat artifact.txt
      
      # 아티팩트 업로드
      - name: 아티팩트 업로드
        uses: actions/upload-artifact@v2
        with:
          name: python-version-artifact
          path: artifact.txt
